### ISSUE TITLE
Customer Meeting #1 Review

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#28]
Let's organize the [Customer Meeting - #1](https://github.com/bounswe/bounswe2018group9/wiki/Customer-Meeting-%231) document to reflect the nature of the meeting.

**Todo**:

- [x] Add the specifics of the meeting.
- [x] Review the answers we had for our questions and document those answers.
- [x] Divide questions into `Clarification` and `Feature` groups. _(Or should we?)_

**Comment by gumityolcu** [comment]
I will do this today, I will need a review. I'll write here when I'm done.

**Comment by gumityolcu** [comment]
It's nearly done. I added all the answers to Clarification Questions except one (Number 3 -with the new enumeration-) because I couldn't find the answer. I transferred the optional feature questions to the (Possible) Feature Questions because the customer gave us the freedom to decide on ourselves about those matters. I also re-enumerated the whole list.

Now, we will be working on requirements after this week too, thus the optional features are not an emergency but we should find the answer to question 3 as soon as possible.

**Comment by kemaltulum** [comment]
I can share what I remember related with third question with my comments:
* Location search should be on a Google Map. You can use either use your location or choose another location to find out the events near the specified point on the map
* Content search is I think related with keywords or tags. For example, when you search for "theatre", you would see all the events including a theatre activity. 
* Semantic search makes me remind that, for example, when you say "theatre in İstanbul", it shouldn't try to match keyword "in", try to find events in İstanbul instead.

I did not want to write these things directly into wiki, since I think there may be some points I missed. Actually,, implementing a search algorithm is a huge thing. We do have much freedom on this topic, I think we can do in the best way possible.

**Comment by serkan-ozel-2015400123** [comment]
I understand them differently @kemaltulum 
1) Content search searches the word you entered directly. i.e It should match with the content literally to show that result to you.
2) Semantic search shows related words & contents also
3) Location based is obvious

However, in that question I was asking whether we should put these searching options seperately or we should put all of them together i.e for all searches we implement all the filters

**Comment by okyksl** [comment]
@gumityolcu I reviewed the document, you are great!

@kemaltulum I think @serkan-ozel-2015400123's description of _semantic search_ is closer to the given initial description of the project. From the document:

> The application should also allow semantic search, which will try to find semantically similar users and events based on the context information provided in the semantic tags. For example, semantic search can be used to retrieve events of similar genres that the user did not specify directly.

However, @kemaltulum's view can be noted as optional feature question.

@serkan-ozel-2015400123 we asked the `question #3`, the answer we get was in these lines:
_Semantic search allows us to search specific tags e.g search all theatre tagged events_.

I think we had a misunderstanding there. So could you please email your question including, _what's semantic search exactly?_, to the customer and document the answer?

**Comment by kemaltulum** [comment]
I think that there is not enough specification on the description. We can design the product in the most convenient way for our users. 

We should first understand or describe what a semantic tag is. The description implies that we should have a search algorithm that is able to suggest events not needing a match with user input. Like Basket Analysis method, we could infere some results in time. For example, one going to a Rock Concert is likely to go to a Jazz Concert, then obviously, this two genres are similar. Our search algorithm should consider such relationships between genres, even though we specify them in the first place. But I think this can be an extra thing as a feature.

Actually, we can dig into details considering real life examples. When you write "tiyatro" on eventbrite.com, it brings you several results which are real theatres at all. Then I suppose that the semantic tag implies that we should specify what an event is. For example, if the user writes "Tarkan concert" we would try to match other concerts as well. In eventbrite case, however, the algorithm probably considers the keyword density in the event description, which is not useful when there is just one "concert" keyword in an event which is a concert.

@serkan-ozel-2015400123 You're right! It seems to be a question that we would have different options for search. I think we should have different result types but no different options at all for search. Modern apps favors the autocomplete system. When user writes our algorithm tries to match based on two things, semantic tags and keywords. The more successful results come first. A location button can activate a map enabling location based searching

**Comment by okyksl** [comment]
I'm closing the issue. If you think there are additional things to clarify about `Customer Meeting #1`, please reopen the issue.
